#Tier 1 Centrifuge Speed
# Default: 1
# Range: > 1
tier1CentrifugeSpeed = 1
#Tier 2 Centrifuge Speed
# Default: 2
# Range: > 1
tier2CentrifugeSpeed = 2
#Tier 3 Centrifuge Speed
# Default: 3
# Range: > 1
tier3CentrifugeSpeed = 3
#Tier 4 Centrifuge Speed
# Default: 4
# Range: > 1
tier4CentrifugeSpeed = 4
#Tier 1 Centrifuge Output Multiplier
# Default: 1
# Range: > 1
tier1CentrifugeOutputMultiplier = 1
#Tier 2 Centrifuge Output Multiplier
# Default: 2
# Range: > 1
tier2CentrifugeOutputMultiplier = 2
#Tier 3 Centrifuge Output Multiplier
# Default: 2
# Range: > 1
tier3CentrifugeOutputMultiplier = 2
#Tier 4 Centrifuge Output Multiplier
# Default: 3
# Range: > 1
tier4CentrifugeOutputMultiplier = 3
#Tier 1 Centrifuge Max Stack Size
# Default: 256
# Range: > 64
tier1CentrifugeMaxStackSize = 256
#Tier 2 Centrifuge Max Stack Size
# Default: 256
# Range: > 64
tier2CentrifugeMaxStackSize = 256
#Tier 3 Centrifuge Max Stack Size
# Default: 512
# Range: > 64
tier3CentrifugeMaxStackSize = 512
#Tier 4 Centrifuge Max Stack Size
# Default: 512
# Range: > 64
tier4CentrifugeMaxStackSize = 512
