[general]
	# General features for the mod.
	# The action to perform when all players are sleeping
	#Allowed Values: Timelapse, SkipTime, Nothing
	sleepAction = "Timelapse"
	# Reset the weather if raining when players wake. Applies to Timelapse and SkipTime.
	resetWeatherOnWake = false

[timelapse]
	# Features for the Timelapse sleepAction
	# If true, performance stats will be written to log on timelapse end (average TPS, total time, total ticks).
	logTimelapsePerformanceStats = true
	# The action to perform on a SLEEPING if they are attacked with DIRECT damage (not a potion/effect) during timelapse. Doesn't apply to Bed Rest.
	#Allowed Values: NoChange, InstantKill, Invincible
	timelapseSleepersDirectDamageAction = "NoChange"
	# For multiplayer. If true, players NOT sleeping will be invincible during Timelapse.
	noDamageToNonSleepers = true
	# For multiplayer. If true, players NOT sleeping will be unable to move during Timelapse.
	noMovementDuringTimelapse = true
	# If true, natural spawning will be disabled during timelapse.
	# Gives a minor speed boost.
	disableNaturalSpawning = true
	# If true, LivingEntity type mobs can not travel during timelapse. Gives a minor speed boost.
	# Disabled by default since it could result in undesired loss, e.g. mobs drowning.
	# Note that this won't apply to players, see noMovementDuringTimelapse for stopping player movement.
	disableLivingEntityTravel = false

[bedRest]
	# Toggle and customize the Bed Rest feature here
	# Allows players to rest in a bed without sleeping, adding a 'Sleep' button next to 'Leave Bed'
	bedRestEnabled = true
	# How much to dim the screen when bed resting. A value below 10 or so will effectively disable the dim. This cannot be a client option because the value is used server-side too.
	# Default: 30
	# Range: 1 ~ 98
	bedRestScreenDimValue = 30

[bedEffectsAndDamage]
	# Customize damage/effect modifiers while bed resting or timelapse. Note that the player will always be kicked out of bed if any damage is allowed to happen.
	# If enabled, poison will not harm the player during bed rest or timelapse.
	bedEffectNoPoison = true
	# If enabled, wither will not harm the player during bed rest or timelapse.
	bedEffectNoWither = true
	# If enabled, hunger (effect) will not apply to the player during bed rest or timelapse.
	bedEffectNoHunger = true

[features]
	# Other features
	# If enabled, allows resting/sleeping in any dimension. Will also disable explosion on use.
	# IMPORTANT - This will ONLY apply with vanilla and vanilla-like beds! Will not change spawn in other dimensions unless featureSetSpawnAnyDimension is also enabled.
	featureAllowAnyDimension = false
	# If enabled, resting/sleeping in a non-overworld bed can ALSO set the spawn to that bed.
	# IMPORTANT - it will *overwrite* the overworld spawn point; it will NOT set per-dimension spawn points!
	# Note that this option may or may not conflict with mod-added custom beds that differ to the vanilla Minecraft bed.
	# This means that if this config is enabled, mod-added custom beds *may* still block it with their own config; or if disabled, mod-added beds *may* still allow setting spawn.
	featureSetSpawnAnyDimension = false
