#Wooden Cobblestone Generator
[wooden_cobble_gen]
	#Speed of the Wooden Cobblestone Generator (ticks per cobblestone)
	# Default: 100
	# Range: > 1
	wooden_cobble_gen_speed = 100
	#The storage capacity of the Wooden Cobblestone Generator
	# Default: 8
	# Range: 1 ~ 64
	wooden_cobble_gen_output = 8
	#Valid blocks for cobblestone generators at any side. Format: "checkforblock;outputblock", it also supports multiple outputblock with comma, if it does not match any then it will return Cobblestone.
	cobbleGenValidBlocks = ["minecraft:stone;minecraft:stone,minecraft:cobblestone", "minecraft:cobblestone;minecraft:cobblestone", "minecraft:deepslate;minecraft:cobbled_deepslate", "minecraft:cobbled_deepslate;minecraft:cobbled_deepslate", "minecraft:tuff;minecraft:tuff", "minecraft:netherrack;minecraft:netherrack", "minecraft:basalt;minecraft:basalt", "minecraft:blackstone;minecraft:blackstone", "minecraft:andesite;minecraft:andesite", "minecraft:diorite;minecraft:diorite", "minecraft:granite;minecraft:granite", "minecraft:end_stone;minecraft:end_stone"]

#Stone Cobblestone Generator
[stone_cobble_gen]
	#Speed of the Stone Cobblestone Generator (ticks per cobblestone)
	# Default: 80
	# Range: > 1
	stone_cobble_gen_speed = 80
	#The storage capacity of the Stone Cobblestone Generator
	# Default: 16
	# Range: 1 ~ 64
	stone_cobble_gen_output = 16
	#Valid blocks for cobblestone generators at any side. Format: "checkforblock;outputblock", it also supports multiple outputblock with comma, if it does not match any then it will return Cobblestone.
	cobbleGenValidBlocks = ["minecraft:stone;minecraft:stone,minecraft:cobblestone", "minecraft:cobblestone;minecraft:cobblestone", "minecraft:deepslate;minecraft:cobbled_deepslate", "minecraft:cobbled_deepslate;minecraft:cobbled_deepslate", "minecraft:tuff;minecraft:tuff", "minecraft:netherrack;minecraft:netherrack", "minecraft:basalt;minecraft:basalt", "minecraft:blackstone;minecraft:blackstone", "minecraft:andesite;minecraft:andesite", "minecraft:diorite;minecraft:diorite", "minecraft:granite;minecraft:granite", "minecraft:end_stone;minecraft:end_stone"]

#Iron Cobblestone Generator
[iron_cobble_gen]
	#Speed of the Iron Cobblestone Generator (ticks per cobblestone)
	# Default: 60
	# Range: > 1
	iron_cobble_gen_speed = 60
	#The storage capacity of the Iron Cobblestone Generator
	# Default: 32
	# Range: 1 ~ 64
	iron_cobble_gen_output = 32
	#Valid blocks for cobblestone generators at any side. Format: "checkforblock;outputblock", it also supports multiple outputblock with comma, if it does not match any then it will return Cobblestone.
	cobbleGenValidBlocks = ["minecraft:stone;minecraft:stone,minecraft:cobblestone", "minecraft:cobblestone;minecraft:cobblestone", "minecraft:deepslate;minecraft:cobbled_deepslate", "minecraft:cobbled_deepslate;minecraft:cobbled_deepslate", "minecraft:tuff;minecraft:tuff", "minecraft:netherrack;minecraft:netherrack", "minecraft:basalt;minecraft:basalt", "minecraft:blackstone;minecraft:blackstone", "minecraft:andesite;minecraft:andesite", "minecraft:diorite;minecraft:diorite", "minecraft:granite;minecraft:granite", "minecraft:end_stone;minecraft:end_stone"]

#Gold Cobblestone Generator
[gold_cobble_gen]
	#Speed of the Gold Cobblestone Generator (ticks per cobblestone)
	# Default: 40
	# Range: > 1
	gold_cobble_gen_speed = 40
	#The storage capacity of the Gold Cobblestone Generator
	# Default: 64
	# Range: 1 ~ 64
	gold_cobble_gen_output = 64
	#Valid blocks for cobblestone generators at any side. Format: "checkforblock;outputblock", it also supports multiple outputblock with comma, if it does not match any then it will return Cobblestone.
	cobbleGenValidBlocks = ["minecraft:stone;minecraft:stone,minecraft:cobblestone", "minecraft:cobblestone;minecraft:cobblestone", "minecraft:deepslate;minecraft:cobbled_deepslate", "minecraft:cobbled_deepslate;minecraft:cobbled_deepslate", "minecraft:tuff;minecraft:tuff", "minecraft:netherrack;minecraft:netherrack", "minecraft:basalt;minecraft:basalt", "minecraft:blackstone;minecraft:blackstone", "minecraft:andesite;minecraft:andesite", "minecraft:diorite;minecraft:diorite", "minecraft:granite;minecraft:granite", "minecraft:end_stone;minecraft:end_stone"]

#Diamond Cobblestone Generator
[diamond_cobble_gen]
	#Speed of the Diamond Cobblestone Generator (ticks per cobblestone)
	# Default: 20
	# Range: > 1
	diamond_cobble_gen_speed = 20
	#The storage capacity of the Diamond Cobblestone Generator
	# Default: 64
	# Range: 1 ~ 64
	diamond_cobble_gen_output = 64
	#Valid blocks for cobblestone generators at any side. Format: "checkforblock;outputblock", it also supports multiple outputblock with comma, if it does not match any then it will return Cobblestone.
	cobbleGenValidBlocks = ["minecraft:stone;minecraft:stone,minecraft:cobblestone", "minecraft:cobblestone;minecraft:cobblestone", "minecraft:deepslate;minecraft:cobbled_deepslate", "minecraft:cobbled_deepslate;minecraft:cobbled_deepslate", "minecraft:tuff;minecraft:tuff", "minecraft:netherrack;minecraft:netherrack", "minecraft:basalt;minecraft:basalt", "minecraft:blackstone;minecraft:blackstone", "minecraft:andesite;minecraft:andesite", "minecraft:diorite;minecraft:diorite", "minecraft:granite;minecraft:granite", "minecraft:end_stone;minecraft:end_stone"]

#Emerald Cobblestone Generator
[emerald_cobble_gen]
	#Speed of the Emerald Cobblestone Generator (ticks per cobblestone)
	# Default: 10
	# Range: > 1
	emerald_cobble_gen_speed = 10
	#The storage capacity of the Emerald Cobblestone Generator
	# Default: 64
	# Range: 1 ~ 64
	emerald_cobble_gen_output = 64
	#Valid blocks for cobblestone generators at any side. Format: "checkforblock;outputblock", it also supports multiple outputblock with comma, if it does not match any then it will return Cobblestone.
	cobbleGenValidBlocks = ["minecraft:stone;minecraft:stone,minecraft:cobblestone", "minecraft:cobblestone;minecraft:cobblestone", "minecraft:deepslate;minecraft:cobbled_deepslate", "minecraft:cobbled_deepslate;minecraft:cobbled_deepslate", "minecraft:tuff;minecraft:tuff", "minecraft:netherrack;minecraft:netherrack", "minecraft:basalt;minecraft:basalt", "minecraft:blackstone;minecraft:blackstone", "minecraft:andesite;minecraft:andesite", "minecraft:diorite;minecraft:diorite", "minecraft:granite;minecraft:granite", "minecraft:end_stone;minecraft:end_stone"]

#Netherite Cobblestone Generator
[netherite_cobble_gen]
	#Speed of the Netherite Cobblestone Generator (ticks per cobblestone)
	# Default: 5
	# Range: > 1
	netherite_cobble_gen_speed = 5
	#The storage capacity of the Netherite Cobblestone Generator
	# Default: 64
	# Range: 1 ~ 64
	netherite_cobble_gen_output = 64
	#Valid blocks for cobblestone generators at any side. Format: "checkforblock;outputblock", it also supports multiple outputblock with comma, if it does not match any then it will return Cobblestone.
	cobbleGenValidBlocks = ["minecraft:stone;minecraft:stone,minecraft:cobblestone", "minecraft:cobblestone;minecraft:cobblestone", "minecraft:deepslate;minecraft:cobbled_deepslate", "minecraft:cobbled_deepslate;minecraft:cobbled_deepslate", "minecraft:tuff;minecraft:tuff", "minecraft:netherrack;minecraft:netherrack", "minecraft:basalt;minecraft:basalt", "minecraft:blackstone;minecraft:blackstone", "minecraft:andesite;minecraft:andesite", "minecraft:diorite;minecraft:diorite", "minecraft:granite;minecraft:granite", "minecraft:end_stone;minecraft:end_stone"]

#Creative Cobblestone Generator
[creative_cobble_gen]
	#Speed of the Creative Cobblestone Generator (ticks per 2 cobblestone)
	# Default: 1
	# Range: > 1
	creative_cobble_gen_speed = 1
	#The storage capacity of the Creative Cobblestone Generator
	# Default: 64
	# Range: 1 ~ 64
	creative_cobble_gen_output = 64
	#The multiplier for the Creative Cobblestone Generator, this will multiply the output by this value
	# Default: 2
	# Range: 1 ~ 32
	creative_cobble_gen_multiplier = 2
	#Valid blocks for cobblestone generators at any side. Format: "checkforblock;outputblock", it also supports multiple outputblock with comma, if it does not match any then it will return Cobblestone.
	cobbleGenValidBlocks = ["minecraft:stone;minecraft:stone,minecraft:cobblestone", "minecraft:cobblestone;minecraft:cobblestone", "minecraft:deepslate;minecraft:cobbled_deepslate", "minecraft:cobbled_deepslate;minecraft:cobbled_deepslate", "minecraft:tuff;minecraft:tuff", "minecraft:netherrack;minecraft:netherrack", "minecraft:basalt;minecraft:basalt", "minecraft:blackstone;minecraft:blackstone", "minecraft:andesite;minecraft:andesite", "minecraft:diorite;minecraft:diorite", "minecraft:granite;minecraft:granite", "minecraft:end_stone;minecraft:end_stone"]
